import { Resend } from 'resend';

function getResend(): Resend {
  const key = process.env.RESEND_API_KEY;
  if (!key) throw new Error('RESEND_API_KEY not set');
  return new Resend(key);
}

const FROM = process.env.EMAIL_FROM ?? 'onboarding@resend.dev';

export interface EmailResult {
  success: boolean;
  messageId?: string;
  error?: string;
}

export async function sendSummaryEmail(opts: {
  to: string;
  recruiterName?: string;
  company?: string;
  roleDiscussed?: string;
  summary: string;
}): Promise<EmailResult> {
  if (!process.env.RESEND_API_KEY) {
    console.warn('[email] RESEND_API_KEY not set — skipping send');
    return { success: false, error: 'Email not configured' };
  }

  const prashantEmail = process.env.PRASHANT_EMAIL ?? '';
  const greeting = opts.recruiterName ? `Hi ${opts.recruiterName},` : 'Hi,';
  const roleNote = opts.roleDiscussed ? ` for the <strong>${opts.roleDiscussed}</strong> role` : '';
  const companyNote = opts.company ? ` at ${opts.company}` : '';

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; max-width: 600px; margin: auto; padding: 24px; }
    h2 { color: #2563eb; }
    .summary { background: #f8fafc; border-left: 4px solid #2563eb; padding: 16px; border-radius: 4px; white-space: pre-wrap; line-height: 1.6; }
    .footer { margin-top: 32px; font-size: 13px; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 16px; }
  </style>
</head>
<body>
  <h2>Conversation Summary — Prashant Rizal</h2>
  <p>${greeting}</p>
  <p>Thanks for your time today! Here's a summary of our conversation${roleNote}${companyNote}.</p>
  <div class="summary">${opts.summary.replace(/\n/g, '<br>')}</div>
  <p style="margin-top:24px">
    If you'd like to speak directly with Prashant or review his work, feel free to reach out at
    <a href="mailto:${prashantEmail}">${prashantEmail}</a>.
  </p>
  <div class="footer">
    This summary was generated by Prashant's AI talent agent.<br>
    Prashant Rizal · QUT Master of IT (graduating June 2026) · Brisbane, Australia
  </div>
</body>
</html>`;

  try {
    const resend = getResend();
    const to = [opts.to, prashantEmail].filter(Boolean);
    const { data, error } = await resend.emails.send({
      from: FROM,
      to,
      subject: `Conversation Summary — Prashant Rizal${opts.roleDiscussed ? ` (${opts.roleDiscussed})` : ''}`,
      html,
    });
    if (error) {
      console.error('[email] resend error:', error);
      return { success: false, error: (error as { message?: string }).message ?? String(error) };
    }
    return { success: true, messageId: data?.id };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error('[email] send failed:', msg);
    return { success: false, error: msg };
  }
}

export async function sendCallNotificationToPrashant(opts: {
  summary?: string;
  transcript?: string;
  endedReason?: string;
  recruiterName?: string;
  recruiterEmail?: string;
  company?: string;
}): Promise<EmailResult> {
  if (!process.env.RESEND_API_KEY) {
    return { success: false, error: 'Email not configured' };
  }

  const prashantEmail = process.env.PRASHANT_EMAIL ?? '';
  if (!prashantEmail) return { success: false, error: 'PRASHANT_EMAIL not set' };

  const who = [opts.recruiterName, opts.company].filter(Boolean).join(' @ ') || 'Unknown caller';
  const endNote = opts.endedReason ? ` (ended: ${opts.endedReason})` : '';

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; max-width: 600px; margin: auto; padding: 24px; }
    h2 { color: #7c3aed; }
    .block { background: #f8fafc; border-left: 4px solid #7c3aed; padding: 16px; border-radius: 4px; white-space: pre-wrap; line-height: 1.6; margin-bottom: 16px; }
    .footer { margin-top: 32px; font-size: 13px; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 16px; }
  </style>
</head>
<body>
  <h2>Voice Call Ended — ${who}${endNote}</h2>
  ${opts.recruiterEmail ? `<p><strong>Recruiter email:</strong> ${opts.recruiterEmail}</p>` : ''}
  ${opts.summary ? `<h3>Summary</h3><div class="block">${opts.summary.replace(/\n/g, '<br>')}</div>` : ''}
  ${opts.transcript ? `<h3>Transcript</h3><div class="block">${opts.transcript.replace(/\n/g, '<br>')}</div>` : ''}
  <div class="footer">Sent automatically by your AI talent agent.</div>
</body>
</html>`;

  try {
    const resend = getResend();
    const { data, error } = await resend.emails.send({
      from: FROM,
      to: prashantEmail,
      subject: `Voice call from ${who}`,
      html,
    });
    if (error) {
      console.error('[email] resend notification error:', error);
      return { success: false, error: (error as { message?: string }).message ?? String(error) };
    }
    return { success: true, messageId: data?.id };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error('[email] call notification failed:', msg);
    return { success: false, error: msg };
  }
}
